yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'
urlpatterns = [
    path('author/', views.AuthorPage.as_view(), name='author'),
    path('tech/', views.TechPage.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_list, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    slug = models.SlugField(max_length=20, unique=True, db_index=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста')
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        related_name='posts',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='comments')

    text = models.TextField(
        help_text='Текст комментария'
    )

    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='follower')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='following')

yatube/posts/forms.py
from .models import Post, Comment
from django.forms import ModelForm


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator
from .models import Post, Group, Follow
from django.contrib.auth import get_user_model
from .forms import PostForm, CommentForm
from django.template import RequestContext
from django.contrib.auth.decorators import login_required

User = get_user_model()


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author).exists()
    post_list = author.posts.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required(redirect_field_name='')
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None,)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return HttpResponseRedirect(reverse('posts:profile',
                                    args=[request.user]))
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return HttpResponseRedirect(reverse('posts:post_detail',
                                    args=[post_id]))
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post
                    )
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('posts:post_detail',
                                    args=[post_id]))
    context = {
        'form': form,
        'is_edit': True,
        'post_id': post.id,
    }
    return render(request, 'posts/create_post.html', context,
                  RequestContext(request))


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'paginator': paginator,
        'page_obj': page
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}    
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}              
        </div>
        <div class="card-body">        
          <form method="post" {% if is_edit %} action ="{% url 'posts:post_edit' post_id %}"
                              {% else %} action ="{% url 'posts:post_create' %}"
                              {% endif %}
                              enctype="multipart/form-data">{% csrf_token %}
            <div class="form-group row my-3 p-3">
              {% for field in form %}
                <p>
                  <label>{{ field.label }}</label>
                  {{ field }}
                </p>
              {% endfor %}
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}    
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}Последние посты избранных авторов{% endblock %}
{% block content %}
<div class="container">
<h1>Последние обновления избранных авторов</h1>
  {% for post in page_obj %}
          <ul>
            <li>
              {{ post.author}}
              <a href={% url 'posts:profile' post.author %}>все посты пользователя</a>
            </li>
            {% load thumbnail %}
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}            
            <li>
              {{ post.pub_date|date }}
            </li>
          </ul>
          <p>{{ post.text|linebreaks  }}</p>
          <a href={% url 'posts:post_detail' post.id %}>подробная информация</a>
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
  </div>
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description|linebreaks }}</p>
  {% for post in page_obj %}
          {% load thumbnail %}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}          
          <ul>
            <li>
              {{ post.author }}
              <a href={% url 'posts:profile' post.author %}>все посты пользователя</a>
            </li>
            <li>
              {{ post.pub_date|date }}
            </li>
          </ul>
          <p>{{ post.text|linebreaks  }}</p>
          <a href={% url 'posts:post_detail' post.id %}>подробная информация</a>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load cache %}
{% cache 20 index_page page_obj%}
  {% for post in page_obj %}
          <ul>
            <li>
              {{ post.author}}
              <a href={% url 'posts:profile' post.author %}>все посты пользователя</a>
            </li>
            {% load thumbnail %}
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}            
            <li>
              {{ post.pub_date|date }}
            </li>
          </ul>
          <p>{{ post.text|linebreaks  }}</p>
          <a href={% url 'posts:post_detail' post.id %}>подробная информация</a>
  {% endfor %}
{% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date }}
            </li>
            {% load thumbnail %}
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
              {% if post.group %}
              <li class="list-group-item">
                Группа: {{ post.group }}
                <a href="{% url 'posts:group' post.group.slug %}">
                  все записи группы
                </a>
              </li>
              {% endif %}
              <li class="list-group-item">
                Автор: {{ post.author }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора:  <span >{{ post.author.posts.count }}</span>
              </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
          
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {{ post.text|linebreaks }}
          </p>
        </article>
        {% if user == post.author %}
        <a href="{% url 'posts:post_edit' post.id %}">
          редактировать
        </a>
        {% endif %}
        {% include 'posts/includes/comment.html' with comments=comments%}
        
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %} <title>Профайл пользователя {{ author.username }} </title> {% endblock %}

{% block content %}
        <article>
          <ul>
            <li>
              Автор: {{ author }}
              <a href="{% url 'posts:profile' author.username %}">все посты пользователя</a>
              {% if following %}
                <a
                  class="btn btn-lg btn-light"
                  href="{% url 'posts:profile_unfollow' author.username %}" role="button"
                >
                  Отписаться
                </a>
              {% else %}
                  <a
                    class="btn btn-lg btn-primary"
                    href="{% url 'posts:profile_follow' author.username %}" role="button"
                  >
                    Подписаться
                  </a>
              {% endif %}
            </li>
          </ul>
          <p>
            {% for post in page_obj %}
            {% load thumbnail %}
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}            
            <p> {{ post.text|linebreaks }} </p>
            <li>
              Дата публикации: {{ post.pub_date|date }}
            </li>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
          </p>
            {% if post.group %}
            <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% endfor %}
        </article>
        <hr>
        {% include 'posts/includes/paginator.html' %}
{% endblock %}